from typing import List,Dict,Any,Optional,TypedDict
from langgraph.graph import START,END,StateGraph
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel,Field
from langchain_core.documents import Document

from src.pull_req_files import fetch_pr_diff
from src.ingestion_and_splitting import process_repo_in_memory
from src.embedding import Embeddings
from src.upsert import Upsert
from src.prompts import query_retrieval_prompt
from src.prompts import rewrite_query_prompt
from src.prompts import grader_prompt
from src.prompts import review_agent_prompt
from src.scale_query import scale_query_function
from src.structured_result_pinecone import pinecone_results_structured


##############
#STATE CLASS #
##############
class State(TypedDict):
    pr_url: str #user input from query
    raw_diff: str #raw diff from PR
    files_changed: List[Dict[str,str]]  #List[{"file_path":"path","raw_diff....":".."}]

    #retrieved context from Pinecone
    retrieved_context: Optional[List[Document]]
    formatted_context_str: Optional[str]
    is_relevant : bool = False #for CRAG

    #counter for CRAG
    counter:int

    #query generated by llm for retrieval
    current_query : Optional[str]

    #final report
    final_report: Optional[str] #Optional matlab None bhi hold kar skta hai

    #bm25 and pinecone objects
    bm25: Optional[Any]
    pinecone_index: Optional[Any]


#grade documents class, pydantic 
class GradeDocuments(BaseModel):
    """Binary score to check relevancy of retrieved context documents"""
    binary_score:str = Field(
        description="documents are relevant to the query: yes or no"
        )


#################
#Graph Function #
#################
def code_review_ai_app(dense_model, llm, namespace):
        """Main function which makes the nodes and the workflow and return final graph"""

        #retrieve the PR Diff Node
        def pull_diff_agent(state: State):
            """#agent that fetches the git PR diffs"""

            query = state["pr_url"] #user will provide this
            output_from_pr = fetch_pr_diff(query)

            return {
                "raw_diff": output_from_pr["raw_diff"],
                "files_changed": output_from_pr["files_changed"],
            }

        
        #retrieve the repository and return chunks of human written code files using Code Aware Splitting
        #then we embedd and upsert to pinecone in the same agent to avoid storing too much data in State class
        def ingest_chunk_embedd_upsert_agent(state: State):
            '''Calls different functions from different code files for data ingestion,
            chunking and embedding then upserting the values to Pinecone'''

            #retrieve chunks
            chunks = process_repo_in_memory(state["pr_url"])

            #retrieve embeddings
            embeddings_obj = Embeddings(dense_model , [chunk.page_content for chunk in chunks]) #send all_text_in_chunks to constructor
            dense_embeddings = embeddings_obj.dense_embeddings_function() 
            sparse_embeddings, bm25 = embeddings_obj.sparse_embeddings_function()
            

            #upsert the data to pinecone
            upsert_obj = Upsert(chunks,dense_embeddings,sparse_embeddings,namespace=namespace)
            upsert_obj.upsert_data() 

            return {"bm25":bm25,   #bm25 object stored in State
                    "pinecone_index":upsert_obj.index
                    }
        

        def retrieve_and_crag(state: State):

            #for scaling the query
            bm25 = state["bm25"]
            #for retrieve the relevant docs
            pinecone_index = state["pinecone_index"]
            #counter
            count = state.get("counter",0) #default 0 agar kuch value nahi hai to

            #first search
            if(count==0):
                #generate a query using PR Diff as context, using llm for query generation
                prompt = ChatPromptTemplate.from_template("""{prompt}\n\nContext:\n{diff}""")
                chain = prompt | llm | StrOutputParser()
                response = chain.invoke({"prompt":query_retrieval_prompt, "diff":state["files_changed"]})


                #rewrite the query and search again, count!=0
            else:
                #re-write a query using PR Diff as context, using llm for query generation
                prompt = ChatPromptTemplate.from_template("""{prompt}\n\nContext:\n{diff}\n\nInitial Query{first_query}""")
                chain = prompt | llm | StrOutputParser()
                response = chain.invoke({"prompt":rewrite_query_prompt, "diff":state["files_changed"], 
                                         "first_query":state["current_query"]})            


            #retrieve the scaled query (dense and sparse)
            scaled_dense, scaled_sparse = scale_query_function(response, dense_model, bm25, alpha=0.5)
                
            #**Check if sparse values are not empty, because if empty :- program will crash**
            has_sparse_data = (
                isinstance(scaled_sparse,dict) #scaled_sparse ek dict ki form mein aata hai
                and len(scaled_sparse.get("indices",[]))>0
                and len(scaled_sparse.get("values",[]))>0
            )

            #payload for query
            query_kwargs = {
                "namespace":namespace,
                "vector":scaled_dense,
                "top_k":17,
                "include_metadata":True,
            }

            #check if has_sparse_data true : which means scaled_sparse empty values nahi return kar raha
            #agar scaled_sparse mein data hai to uusko bhi query_kwargs mein daaldo
            #and if scaled_sparse is empty, then our search will become purely Semantic Search
            if has_sparse_data:
                query_kwargs["sparse_vector"] = scaled_sparse

            results = pinecone_index.query(**query_kwargs) # '**' will convert dictionary keys into function arguments

            structured_result_for_context: List[Document] = pinecone_results_structured(results)

            return {
                "current_query":response,
                "retrieved_context":structured_result_for_context,
                "counter":count+1 #increment count
            }


        def grader_agent(state:State):
            """Grades the documents, returns 'yes' if relevant and 'no if documents are irrelevant'"""

            retrieved_docs_pinecone = state["retrieved_context"]
            query = state['current_query']

            chain = ChatPromptTemplate.from_template(grader_prompt) | llm.with_structured_output(GradeDocuments)

            #structure retrieved docs(List[Documents]) in a manner that it is readable by llm
            formatted_context = []
            for doc in retrieved_docs_pinecone:
                block = f"---File {doc.metadata.get('file_path',"N/A")}\nScore:{doc.metadata.get('score',0)}\nPage Content:\n{doc.page_content}"
                formatted_context.append(block)
            context_str = "\n\n".join(formatted_context)

            response = chain.invoke({"query":query, "documents":context_str})
            is_rel = (response.binary_score.lower().strip() == 'yes')#True if:'yes', else False

            return{
                "is_relevant": is_rel, 
                "formatted_context_str":context_str
            }

        def router_agent(state:State):

            MAX_RETRIES = 2

            """Checks is_relevant from state, if true then routes to generate final review report
            and if false then routes to retrieve_and_crag to again write another query and search"""

            is_rel: bool = state.get("is_relevant", False)
            count: int = state.get("counter", 0)

            #if docs relevant
            if is_rel:
                return "review_agent"

            #if max retries reached or exceeded, then force review on existing cotext
            if count>=MAX_RETRIES:
                return "review_agent"

            #default return condition, that'll be to re-write the query
            return "retrieve_and_crag"


        def review_agent(state:State):
            context_str = state["formatted_context_str"]
            pr_diff = state["files_changed"]

            prompt = ChatPromptTemplate.from_template(review_agent_prompt)
            chain = prompt | llm | StrOutputParser()

            review_report = chain.invoke({
                "files_changed":pr_diff,
                "context":context_str,
            })

            return {"final_report":review_report}
            



        ####################
        #Workflow and Graph#
        ####################

        workflow = StateGraph(State)

        #add nodes
        workflow.add_node("pull_diff",pull_diff_agent)
        workflow.add_node("ingestion_and_chunk",ingest_chunk_embedd_upsert_agent)
        workflow.add_node("retrieve_and_crag",retrieve_and_crag)
        workflow.add_node("grader_agent",grader_agent)
        workflow.add_node("review_agent",review_agent)

        #add edges
        workflow.add_edge(START,"pull_diff")
        workflow.add_edge("pull_diff","ingestion_and_chunk")
        workflow.add_edge("ingestion_and_chunk","retrieve_and_crag")
        workflow.add_edge("retrieve_and_crag","grader_agent")
        workflow.add_conditional_edges(
            "grader_agent",
            router_agent,
            {
                "review_agent": "review_agent",
                "retrieve_and_crag": "retrieve_and_crag"
            }
        )
        workflow.add_edge("review_agent",END)

        #compile
        graph = workflow.compile()

        return graph